### PR TITLE
Fix download using too much memory

### PR DESCRIPTION
**Pull request by adrienbrault**

### CODE REVIEW

**Comment by josiasmontag** [comment]
Can you explain why your implementation uses less memory than the current one? It currently uses streams as well?

**Comment by adrienbrault** [comment]
```
$local->write($download);
```

`Psr\Http\Message\StreamInterface::write` expects a string. However `$download` is a StreamInterface, so `Psr\Http\Message\StreamInterface::__toString` is implicitly called ( https://github.com/guzzle/psr7/blob/31ea59d632d3ac145300fffb2873a195172c0814/src/Stream.php#L249 )

**Comment by josiasmontag** [comment]
Thanks!

**Comment by m4tthumphrey** [comment]
This caused an issue in production for me when I just updated to 2.2.1:

> stream_copy_to_stream() expects parameter 2 to be resource

I was passing an instance of `Psr\Http\Message\StreamInterface` to the `Cloudconvert\Process::downloadStream()` method. This worked fine before because [L157](https://github.com/cloudconvert/cloudconvert-php/pull/55/commits/1fdd7f210c9121d0eb27977c026bdb9bf4452843#diff-8c37257f65f0ffc175f513be851fb33bL157) handled this. The change has removed this functionality so that the `$stream` argument is passed directly to `stream_copy_to_stream()` which only accepts a `resource`.

I understand that the method expects a `resource` and not `StreamInterface` however it worked correctly before so this comment is more of a warning to others incase they are doing the same.

I have not worked enough with Psr7 streams to come up with a decent solution yet so I have just rolled back to 2.2.0 for now but will revisit this to look at a proper solution when I have time.

**Pull request merged**
