### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by bobmulder**
Unfortunately I was not able to install the newest version of this package because of out-dated dependencies. Hopefully this will solve my issues...

### CODE REVIEW

**Comment by bobmulder** [comment]
Thanks for merging, @josiasmontag. Can you create a new release?

**Comment by josiasmontag** [comment]
There is already - 3.0.3.

**Comment by bobmulder** [comment]
Github's fault, it tried to hide them for me ;P Thank you!

**Comment by bobmulder** [comment]
Trying to install 3.0.3, but is not working. Running `composer why-not cloudconvert/cloudconvert-php:3.0.3` returns: 

```
cloudconvert/cloudconvert-php  3.0.3       requires          php-http/client-implementation (^1.0)
my-application/dev             dev-master  does not require  php-http/client-implementation (but v2.0.1 is installed)
```

Setting the following in `composer.json` does not work for me:
```
    "php-http/client-implementation": "^1.0 || ^2.0",
```

Any suggestions?

**Pull request merged**
